### ISSUE TITLE
Support editing FLAC album art

### ISSUE THREAD

**Issue by TobTobXX** [knuxify/eartag#14]
Hi! Your project is awesome! Thank you for your work.

I just wanted to ask if editing (setting/replacing/removing) album art is in the scope of this application. I tried editing a flac file, but couldn't see an option, while the screenshots in the flatpak listing show an album art.

**Comment by knuxify** [comment]
Editing album art is possible, but only with mp3 files; this is due to the fact that pytaglib (the library we use for non-MP3 files) doesn't have a way to edit the album cover. eyed3 (the library we use for MP3 files) does support this. Technically taglib itself can edit the raw id3 data, which would allow us to set the covers (in some incredibly hacky way)... if pytaglib actually allowed us to edit that raw data.

Still, this is something I considered - the idea I had was to add additional file handlers that use other libraries depending on the filetype that's opened (kind of like we already do with eyed3 vs pytaglib - see https://github.com/knuxify/eartag/blob/main/src/file.py). I didn't get around to finding any libraries that would fit - if there's some alternative to pytaglib that works with the usual file formats (at least WAV, FLAC and OGG), but also supports editing album art, I'd be happy to add support for it.

(Admittedly, this is also a bit of a documentation issue - I didn't actually mention any of this anywhere. Whoops.)

**Comment by TobTobXX** [comment]
No worries, it's a young project, lots of time to sort through this.

I don't know about python libraries, but libFLAC, the "official" flac library (a C/C++ library) is rather nice to work with, especially the metadata parts. So I'd imagine there to be some useable libraries. Imma look out, but I'm not proficient in python, so can't tell if I'll be able to contribute. However, flac's metadata tends to be always easier than ID3. To me ID3's picture metadata always seemed very badly implemented, while flac has a clear concept of pictures with certain functions (eg. Cover (front), Publisher, Cover (back), etc...).

**Comment by knuxify** [comment]
I did some digging and found that [Mutagen has support for Vorbis Comment](https://mutagen.readthedocs.io/en/latest/user/vcomment.html), which is used in OGG and FLAC files. (Funnily enough, I actually used Mutagen for file editing when I initially started the project, but the lack of album cover support in the simple API scared me off... here though, it's neatly explained in the documentation, and we already have other libraries to handle those cases instead.)

The only wrapper around libFLAC i could find was [pyflac](https://pyflac.readthedocs.io/en/latest), which doesn't support reading/writing metadata.

**Comment by TobTobXX** [comment]
Wow, that was... insanely quick? Thank you!
