### ISSUE TITLE
Album Art Doesn't Show Up For M4A Music Files

### ISSUE THREAD

**Issue by adarsh1001** [knuxify/eartag#53]
### Describe the issue

Steps to Reproduce:
1. Open any `.m4a` file (with or without an existing album art) with EarTag.
2. Even though all the text metadata fields are present and editable, the album art doesn't show up (screenshot attached).

![Screenshot_2022-12-10_03-13-25](https://user-images.githubusercontent.com/8820038/206801102-bfb92a25-d965-4eee-b67a-6dbf9def2f8b.png)

### Additional information
1. EarTag 0.2.1 (Flatpak)
2. KDE 5.26.3 with X11

**Comment by knuxify** [comment]
This is the same issue as in #27 (both ALAC and m4a files are technically mp4), where Ear Tag didn't have a proper backend for mp4 files, so it used the pytaglib backend which didn't support cover art.

This is now fixed with #48 (which added a proper backend to handle those files), although it hasn't made it into a release yet; it will be a part of 0.3.0 when it releases in the next week or two.

**Comment by adarsh1001** [comment]
Ah I see, thanks for the info 🙌
