### ISSUE TITLE
Missing python-modules.json

### ISSUE THREAD

**Issue by sabriunal** [knuxify/eartag#62]
There is no 'python-modules.json' file in the Eartag repository, but it is listed in 'Flatpak.json' at this link: https://github.com/knuxify/eartag/blob/main/app.drey.EarTag.json#L29. 

However, there is a 'python-modules.json' file available on the Flathub GitHub repository: https://github.com/flathub/app.drey.EarTag/blob/master/python-modules.json.

**Comment by knuxify** [comment]
There already is a flatpak-python-modules.json file, but here it's in the data directory: https://github.com/knuxify/eartag/blob/main/data/flatpak-python-modules.json

Seems like I didn't set the path up correctly. (These oversights do happen, as I use the `./run` script to run Ear Tag, rather than GNOME Builder, so I don't notice if the flatpak manifest breaks.)
