### ISSUE TITLE
App won't launch

### ISSUE THREAD

**Issue by PS-Professional** [knuxify/eartag#67]
### Describe the issue

Hi there.
I compiled and installed this application on my system but it won't launch.
Here is the console output:
```
Traceback (most recent call last):
  File "/usr/local/bin/eartag", line 57, in <module>
    from eartag import main
  File "/usr/local/share/eartag/eartag/main.py", line 39, in <module>
    from .window import EartagWindow
  File "/usr/local/share/eartag/eartag/window.py", line 30, in <module>
    from .fileview import EartagFileView
  File "/usr/local/share/eartag/eartag/fileview.py", line 29, in <module>
    from .file import eartagfile_from_path
  File "/usr/local/share/eartag/eartag/file.py", line 413, in <module>
    class EartagRemovalDiscardWarningDialog(Adw.MessageDialog):
  File "/usr/lib/python3/dist-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'MessageDialog'
```

### Additional information

Distro: Ubuntu 22.04.01
Python version: 3.10.6
Self-built package

**Comment by knuxify** [comment]
The libadwaita version in Ubuntu 22.04 is 1.1.0 (see https://packages.ubuntu.com/jammy/libadwaita-1-0), which does not contain AdwMessageDialog (added in 1.2.0), as well as AdwEntryRow and AdwAboutWindow. This unfortunately means that Ear Tag 0.3.0 and above won't run on Ubuntu 22.04.

If you want to use the package natively, you might have better luck with Ear Tag 0.2.1. Otherwise, I'd suggest using the Flatpak version. (There isn't a snap package for Ear Tag, I might consider making one but I'm not a snap user.)

**Comment by knuxify** [comment]
(Alternatively, you might have some luck [installing the libadwaita package from Ubuntu 22.10](https://packages.ubuntu.com/kinetic/libadwaita-1-0) but I wouldn't recommend it.)
